version: '3'
services:
  change_pdf_name:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./output:/app/output
    command: sh -c "java -jar change_pdf_name.jar && cd /app/files && zip -r /app/output/output.zip new/*"
